### ISSUE TITLE
[Feature request] Add an option to cleanup command to remove sections from script

### ISSUE THREAD

**Issue by dtritus** [tp7/Prass#2]
It would be useful to have an option to remove sections like `[Fonts]` or `[Aegisub Project Garbage]` from script.

**Comment by tp7** [comment]
It now should be possible to pass something like `cleanup --sections fonts --sections aegi`, where aegi stands for aegisub project garbage. Full list in the help as usual.

The command line stuff is not finalized so feel free to suggest a better api if you have one in mind. I realize that specifying multiple sections with a comma would be shorter, but it's a bit harder to do, makes help messages less useful out of the box and I'm just not sure it's worth it.

**Comment by dtritus** [comment]
Works great, thanks.

Regarding command line api, I think that current api is good enough.
